import { BaseImportService } from "./baseImportService";
import { ImportSourceEnum } from "@workspace/db";

/**
 * Indeed job import service
 */
export class IndeedImportService extends BaseImportService {
  constructor() {
    super("indeed" as ImportSourceEnum);
  }

  /**
   * Generate Indeed-specific mock data
   */
  protected getMockData(): Array<any> {
    return [
      // IBM India (10 jobs)
      {
        title: "Senior Software Engineer",
        company: "IBM India",
        location: "Bangalore, Karnataka",
        workMode: "hybrid",
        experienceLevel: "senior",
        salaryMin: 1500000,
        salaryMax: 2200000,
        salaryCurrency: "INR",
        description: "Develop cloud and AI solutions for enterprise clients.",
        skills: ["Java", "Python", "Cloud", "AI", "Machine Learning"],
        applyUrl: "https://indeed.com/viewjob?jk=300001",
        postedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
      },
      {
        title: "Full Stack Developer",
        company: "IBM India",
        location: "Pune, Maharashtra",
        workMode: "hybrid",
        experienceLevel: "mid-level",
        salaryMin: 900000,
        salaryMax: 1300000,
        salaryCurrency: "INR",
        description: "Build web applications using React and Node.js.",
        skills: ["React", "Node.js", "MongoDB", "Express", "JavaScript"],
        applyUrl: "https://indeed.com/viewjob?jk=300002",
        postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
      {
        title: "Data Scientist",
        company: "IBM India",
        location: "Hyderabad, Telangana",
        workMode: "remote",
        experienceLevel: "senior",
        salaryMin: 1800000,
        salaryMax: 2500000,
        salaryCurrency: "INR",
        description: "Work on Watson AI and data science projects.",
        skills: ["Python", "R", "Watson", "Machine Learning", "SQL"],
        applyUrl: "https://indeed.com/viewjob?jk=300003",
        postedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        title: "DevOps Engineer",
        company: "IBM India",
        location: "Chennai, Tamil Nadu",
        workMode: "onsite",
        experienceLevel: "mid-level",
        salaryMin: 1000000,
        salaryMax: 1500000,
        salaryCurrency: "INR",
        description: "Manage CI/CD pipelines for cloud-native applications.",
        skills: ["AWS", "Azure", "Docker", "Kubernetes", "Jenkins"],
        applyUrl: "https://indeed.com/viewjob?jk=300004",
        postedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },
      {
        title: "UI/UX Designer",
        company: "IBM India",
        location: "Kolkata, West Bengal",
        workMode: "remote",
        experienceLevel: "mid-level",
        salaryMin: 600000,
        salaryMax: 900000,
        salaryCurrency: "INR",
        description: "Design user interfaces for enterprise software products.",
        skills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
        applyUrl: "https://indeed.com/viewjob?jk=300005",
        postedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        title: "Database Administrator",
        company: "IBM India",
        location: "Noida, Uttar Pradesh",
        workMode: "onsite",
        experienceLevel: "mid-level",
        salaryMin: 800000,
        salaryMax: 1200000,
        salaryCurrency: "INR",
        description: "Administer and optimize database systems.",
        skills: ["SQL", "Oracle", "DB2", "MongoDB", "Backup Recovery"],
        applyUrl: "https://indeed.com/viewjob?jk=300006",
        postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: "Network Engineer",
        company: "IBM India",
        location: "Gurgaon, Haryana",
        workMode: "onsite",
        experienceLevel: "senior",
        salaryMin: 1200000,
        salaryMax: 1700000,
        salaryCurrency: "INR",
        description: "Design and implement network solutions for data centers.",
        skills: ["Cisco", "Juniper", "Networking", "CCNP", "SD-WAN"],
        applyUrl: "https://indeed.com/viewjob?jk=300007",
        postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        title: "Business Analyst",
        company: "IBM India",
        location: "Ahmedabad, Gujarat",
        workMode: "remote",
        experienceLevel: "mid-level",
        salaryMin: 700000,
        salaryMax: 1000000,
        salaryCurrency: "INR",
        description: "Analyze business processes and recommend improvements.",
        skills: ["SQL", "Tableau", "Power BI", "Excel", "Process Modeling"],
        applyUrl: "https://indeed.com/viewjob?jk=300008",
        postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
      {
        title: "Technical Support Engineer",
        company: "IBM India",
        location: "Jaipur, Rajasthan",
        workMode: "onsite",
        experienceLevel: "entry-level",
        salaryMin: 400000,
        salaryMax: 600000,
        salaryCurrency: "INR",
        description: "Provide technical support for hardware and software products.",
        skills: ["Windows", "Linux", "Networking", "Troubleshooting", "ITIL"],
        applyUrl: "https://indeed.com/viewjob?jk=300009",
        postedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        title: "Project Manager",
        company: "IBM India",
        location: "Bangalore, Karnataka",
        workMode: "hybrid",
        experienceLevel: "senior",
        salaryMin: 1300000,
        salaryMax: 1900000,
        salaryCurrency: "INR",
        description: "Lead software development projects from inception to delivery.",
        skills: ["PMP", "Agile", "Scrum", "Jira", "Risk Management"],
        applyUrl: "https://indeed.com/viewjob?jk=300010",
        postedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },

      // Oracle India (10 jobs)
      {
        title: "Software Engineer",
        company: "Oracle India",
        location: "Bangalore, Karnataka",
        workMode: "hybrid",
        experienceLevel: "mid-level",
        salaryMin: 1000000,
        salaryMax: 1500000,
        salaryCurrency: "INR",
        description: "Develop database tools and enterprise software.",
        skills: ["Java", "SQL", "PL/SQL", "Oracle Database", "REST"],
        applyUrl: "https://indeed.com/viewjob?jk=300011",
        postedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
      },
      {
        title: "Senior Software Engineer",
        company: "Oracle India",
        location: "Hyderabad, Telangana",
        workMode: "remote",
        experienceLevel: "senior",
        salaryMin: 1500000,
        salaryMax: 2200000,
        salaryCurrency: "INR",
        description: "Lead development of cloud infrastructure and services.",
        skills: ["Java", "Python", "Cloud", "Microservices", "Docker"],
        applyUrl: "https://indeed.com/viewjob?jk=300012",
        postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
      {
        title: "Cloud Engineer",
        company: "Oracle India",
        location: "Pune, Maharashtra",
        workMode: "onsite",
        experienceLevel: "mid-level",
        salaryMin: 900000,
        salaryMax: 1300000,
        salaryCurrency: "INR",
        description: "Manage Oracle Cloud Infrastructure services.",
        skills: ["OCI", "AWS", "Azure", "Linux", "Networking"],
        applyUrl: "https://indeed.com/viewjob?jk=300013",
        postedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        title: "Database Administrator",
        company: "Oracle India",
        location: "Chennai, Tamil Nadu",
        workMode: "onsite",
        experienceLevel: "senior",
        salaryMin: 1200000,
        salaryMax: 1800000,
        salaryCurrency: "INR",
        description: "Administer and optimize Oracle databases for performance.",
        skills: ["Oracle DBA", "SQL", "PL/SQL", "RAC", "Data Guard"],
        applyUrl: "https://indeed.com/viewjob?jk=300014",
        postedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },
      {
        title: "Applications Developer",
        company: "Oracle India",
        location: "Noida, Uttar Pradesh",
        workMode: "hybrid",
        experienceLevel: "mid-level",
        salaryMin: 800000,
        salaryMax: 1200000,
        salaryCurrency: "INR",
        description: "Develop applications using Oracle Fusion Middleware.",
        skills: ["Java", "SOA", "WebLogic", "ADF", "JDeveloper"],
        applyUrl: "https://indeed.com/viewjob?jk=300015",
        postedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        title: "Technical Consultant",
        company: "Oracle India",
        location: "Pune, Maharashtra",
        workMode: "remote",
        experienceLevel: "mid-level",
        salaryMin: 800000,
        salaryMax: 1200000,
        salaryCurrency: "INR",
        description: "Provide technical expertise on Oracle products to clients.",
        skills: ["Oracle", "SQL", "Java", "Presales", "Solution Design"],
        applyUrl: "https://indeed.com/viewjob?jk=300016",
        postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: "Quality Assurance Engineer",
        company: "Oracle India",
        location: "Chennai, Tamil Nadu",
        workMode: "onsite",
        experienceLevel: "mid-level",
        salaryMin: 600000,
        salaryMax: 900000,
        salaryCurrency: "INR",
        description: "Test Oracle software products and solutions.",
        skills: ["Selenium", "QTP", "LoadRunner", "Manual Testing", "Test Management"],
        applyUrl: "https://indeed.com/viewjob?jk=300017",
        postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        title: "User Experience Designer",
        company: "Oracle India",
        location: "Bangalore, Karnataka",
        workMode: "remote",
        experienceLevel: "mid-level",
        salaryMin: 700000,
        salaryMax: 1000000,
        salaryCurrency: "INR",
        description: "Design user experiences for Oracle cloud applications.",
        skills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
        applyUrl: "https://indeed.com/viewjob?jk=300018",
        postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
      {
        title: "Network Administrator",
        company: "Oracle India",
        location: "Gurgaon, Haryana",
        workMode: "onsite",
        experienceLevel: "entry-level",
        salaryMin: 350000,
        salaryMax: 550000,
        salaryCurrency: "INR",
        description: "Manage and maintain network infrastructure.",
        skills: ["Cisco", "Juniper", "Networking", "CCNA", "Troubleshooting"],
        applyUrl: "https://indeed.com/viewjob?jk=300019",
        postedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        title: "Technical Writer",
        company: "Oracle India",
        location: "Noida, Uttar Pradesh",
        workMode: "remote",
        experienceLevel: "mid-level",
        salaryMin: 400000,
        salaryMax: 700000,
        salaryCurrency: "INR",
        description: "Create documentation for Oracle software products.",
        skills: ["Technical Writing", "Markdown", "XML", "API Documentation", "MadCap Flare"],
        applyUrl: "https://indeed.com/viewjob?jk=300020",
        postedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },

      // Deloitte India (10 jobs)
      {
        title: "Senior Consultant",
        company: "Deloitte India",
        location: "Mumbai, Maharashtra",
        workMode: "hybrid",
        experienceLevel: "senior",
        salaryMin: 1400000,
        salaryMax: 2100000,
        salaryCurrency: "INR",
        description: "Provide consulting services for finance and risk management.",
        skills: ["Consulting", "Financial Analysis", "Risk Management", "PowerPoint", "Excel"],
        applyUrl: "https://indeed.com/viewjob?jk=300021",
        postedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
      },
      {
        title: "Technology Analyst",
        company: "Deloitte India",
        location: "Bangalore, Karnataka",
        workMode: "remote",
        experienceLevel: "mid-level",
        salaryMin: 800000,
        salaryMax: 1200000,
        salaryCurrency: "INR",
        description: "Analyze technology trends and recommend solutions.",
        skills: ["Technology Analysis", "Research", "Report Writing", "Presentation", "Excel"],
        applyUrl: "https://indeed.com/viewjob?jk=300022",
        postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
      {
        title: "Software Engineer",
        company: "Deloitte India",
        location: "Hyderabad, Telangana",
        workMode: "hybrid",
        experienceLevel: "mid-level",
        salaryMin: 700000,
        salaryMax: 1000000,
        salaryCurrency: "INR",
        description: "Develop software solutions for audit and tax practices.",
        skills: ["Java", "Python", "SQL", ".NET", "Cloud"],
        applyUrl: "https://indeed.com/viewjob?jk=300023",
        postedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        title: "Data Scientist",
        company: "Deloitte India",
        location: "Pune, Maharashtra",
        workMode: "remote",
        experienceLevel: "senior",
        salaryMin: 1600000,
        salaryMax: 2300000,
        salaryCurrency: "INR",
        description: "Apply analytics and machine learning to solve business problems.",
        skills: ["Python", "R", "Machine Learning", "Tableau", "SQL"],
        applyUrl: "https://indeed.com/viewjob?jk=300024",
        postedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },
      {
        title: "Risk Analyst",
        company: "Deloitte India",
        location: "Chennai, Tamil Nadu",
        workMode: "onsite",
        experienceLevel: "mid-level",
        salaryMin: 700000, // Fixed the sliderMin typo from original
        salaryMax: 1000000,
        salaryCurrency: "INR",
        description: "Assess and manage financial and operational risks.",
        skills: ["Risk Management", "Statistics", "Modeling", "Excel", "SQL"],
        applyUrl: "https://indeed.com/viewjob?jk=300025",
        postedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        title: "HR Specialist",
        company: "Deloitte India",
        location: "Kolkata, West Bengal",
        workMode: "onsite",
        experienceLevel: "entry-level",
        salaryMin: 400000,
        salaryMax: 600000,
        salaryCurrency: "INR",
        description: "Support human resources functions and employee relations.",
        skills: ["HR", "Recruitment", "Onboarding", "Employee Engagement", "HRIS"],
        applyUrl: "https://indeed.com/viewjob?jk=300026",
        postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: "Finance Analyst",
        company: "Deloitte India",
        location: "Noida, Uttar Pradesh",
        workMode: "remote",
        experienceLevel: "mid-level",
        salaryMin: 600000,
        salaryMax: 900000,
        salaryCurrency: "INR",
        description: "Analyze financial data and prepare reports for clients.",
        skills: ["Financial Analysis", "Budgeting", "Forecasting", "Excel", "Financial Modeling"],
        applyUrl: "https://indeed.com/viewjob?jk=300027",
        postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: "Cloud Engineer",
        company: "Deloitte India",
        location: "Ahmedabad, Gujarat",
        workMode: "onsite",
        experienceLevel: "mid-level",
        salaryMin: 800000,
        salaryMax: 1200000,
        salaryCurrency: "INR",
        description: "Implement and manage cloud infrastructure for clients.",
        skills: ["AWS", "Azure", "Docker", "Kubernetes", "Terraform"],
        applyUrl: "https://indeed.com/viewjob?jk=300028",
        postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        title: "Business Analyst",
        company: "Deloitte India",
        location: "Pune, Maharashtra",
        workMode: "remote",
        experienceLevel: "mid-level",
        salaryMin: 600000,
        salaryMax: 900000,
        salaryCurrency: "INR",
        description: "Analyze business processes and recommend improvements.",
        skills: ["SQL", "Tableau", "Power BI", "Excel", "Process Modeling"],
        applyUrl: "https://indeed.com/viewjob?jk=300029",
        postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
      {
        title: "Assistant Manager",
        company: "Deloitte India",
        location: "Bangalore, Karnataka",
        workMode: "onsite",
        experienceLevel: "senior",
        salaryMin: 1100000,
        salaryMax: 1600000,
        salaryCurrency: "INR",
        description: "Assist in managing client engagements and delivery teams.",
        skills: ["Project Management", "Client Management", "Delivery Excellence", "People Management"],
        applyUrl: "https://indeed.com/viewjob?jk=300030",
        postedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      }
    ];
  }
}